api_platform:
    title: 'Sinuzoid API'
    description: 'Users gestion API'
    version: '1.0.0'
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
    docs_formats:
        json: ['application/json']
        html: ['text/html']
    enable_docs: true
    enable_entrypoint: true
